services:
  anydoor:
    build: .
    container_name: anydoor
    volumes:
      - ./models:/usr/src/app/models
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use count: all for all GPUs
              capabilities: [gpu]